language: node_js

notifications:
  email: false

node_js:
- '6'

before_script:
- npm prune
- npm install -g firebase-tools

script:
- npm run test:headless

after_success:
- npm run build
- firebase deploy --token=${FIREBASE_API_TOKEN}

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
  only:
  - master
