language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
script:
  - npm run test:headless
after_success:
  - npm run semantic-release
  - npm run deploy -- --token=${FIREBASE_API_TOKEN}
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
